### ISSUE TITLE
Infer the token contract address when removing a token

### ISSUE THREAD

**Issue by lkngtn** [1Hive/redemptions-app#26]
Currently removing a token requires a user to input the token contract address, but since the user is clicking on the specific token icon in order to remove the token it would make sense for this to be inferred from that action.

**Comment by fabriziovigevani** [comment]
Actually, the address is inferred from the action when the user clicks on the token icon. 
The sidepanel opens with the token address to remove already on the input, and the input is disabled so that it cannot be changed.

Maybe we could edit the input style so it appears as a normal text in this case.

**Comment by lkngtn** [comment]
My bad!

And agree not having it in a text box that looks editable would probably be a bit clearer!

**Comment by rperez89** [comment]
@lkngtn would be a nice to have show it as a badge?

<img width="329" alt="Screen Shot 2019-06-03 at 5 39 47 PM" src="https://user-images.githubusercontent.com/11763623/58833107-bbd9c080-8626-11e9-87b9-a7b5f21c5745.png">
