### ISSUE TITLE
Tried to run this locally

### ISSUE THREAD

**Issue by lkngtn** [1Hive/redemptions-app#7]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/4986634/57822804-28b61500-7763-11e9-988b-5c8ff4eb9e88.png">

Seem to be getting stuck here. not sure why... any ideas?

**Comment by 0xGabi** [comment]
I just check and the problem is related on how `aragon run` works.
In this case as the Redemptions initialize function need the Vault, TokenManager and an array of address you need to run like this: `aragon run --app-init <vaul-address> <token-manager-address> [ ]`
Better just use the template we made with @rperez89 to have a dao with a vault and token-manager already initialized in the redemptions app.
Run it with: `aragon run --template Template --template-init @ARAGON_ENS` or `npm run start:ipfs:template`.
I'll add it in the Readme
